### ISSUE TITLE
Granulator doesn't appear to work with custom file

### ISSUE THREAD

**Issue by fiebrink1** [fiebrink1/Sound_Control#12]
Have tried with both wav and aiff on Mac. File name shows up below "custom" but doesn't play. Clicking on "custom (drop file)" changes message below to "Custom Sound: No Sound."

**Comment by MartinTownley** [comment]
Resolved: the granulator patch has a drop file object, which is as large as the entire window so that the file can be dropped anywhere. However, the object needs to be in front of all the others for this functionality to work, which it wasn't (and it now is).
