### ISSUE TITLE
Colour tracker isn't reloading last used colour/tolerance

### ISSUE THREAD

**Issue by fiebrink1** [fiebrink1/Sound_Control#14]
Tested this on Mac but not windows yet

**Comment by MartinTownley** [comment]
Colour Tracker (not multi) now recalls last used settings. A specified dictionary has been created for the purpose, an alias of which exists in the main patch – this means that the settings remain retrievable after the instrument patch has closed, and they can then be recalled again upon creation of a new instrument patch.

Next is to implement same logic for Multi-Colour tracker.
