### ISSUE TITLE
Micro:bit "connected" acts as a button, not just an indicator

### ISSUE THREAD

**Issue by fiebrink1** [fiebrink1/Sound_Control#17]
In Micro:bit position and touch via bluetooth, the "Connected" indicator acts as a button when there's no micro:bit connected. We should disable clicking on this so it's an indicator only, to avoid people thinking they need to click on it in order to connect.

**Comment by MartinTownley** [comment]
Resolved: used "script ignoreclick" messages so that the buttons no longer respond to clicks.

**Comment by fiebrink1** [comment]
***Auto-reply follows***
FYI: I am about to go on maternity leave and so I am only responding to high-priority emails at this time while I work on wrapping up existing projects and supervision work. If you are a Computing student, I suggest you email the Computing office (computing@gold.ac.uk) and to find out how to best redirect your query.
________________________________

**Comment by fiebrink1** [comment]
***Auto-reply follows***
FYI: I am about to go on maternity leave and so I am only responding to high-priority emails at this time while I work on wrapping up existing projects and supervision work. If you are a Computing student, I suggest you email the Computing office (computing@gold.ac.uk) and to find out how to best redirect your query.
________________________________
